rubykube/barong

Gemfile
Gemfile.lock
app/assets/javascripts/admin.js
app/assets/stylesheets/admin.sass
app/controllers/admin/dashboard_controller.rb
app/views/admin/accounts/index.html.erb
app/views/admin/dashboard/index.html.erb
app/views/admin/shared/_navigation.html.erb
app/views/layouts/admin.html.erb
app/views/layouts/web.html.erb
config/environments/development.rb
config/routes.rb

Add BS4 for admin & navigation.

---

Dockerfile
config/initializers/devise.rb
config/secrets.yml

Set devise secret on container build

---

app/controllers/index_controller.rb
app/controllers/profiles_controller.rb
app/helpers/application_helper.rb
app/views/layouts/application.html.erb
spec/features/admin_sign_in_spec.rb
spec/features/manage_users_spec.rb
spec/features/phone_verification_spec.rb
spec/features/sign_in_spec.rb
spec/features/sign_up_spec.rb

Took header and footer out of card div.
Redirect not signed in user to sign in page
Redirect user that has profile to documents/new

Small improvements

---

app/controllers/admin/profiles_controller.rb
app/views/admin/accounts/index.html.erb
app/views/admin/profiles/index.html.erb
app/views/admin/websites/index.html.erb

Unifying styles in the admin panel

Unifying styles in the admin panel

---

app/assets/stylesheets/web/devise.scss
app/views/index/index.html.erb
spec/features/phone_verification_spec.rb
spec/views/profiles/edit.html.erb_spec.rb
spec/views/profiles/new.html.erb_spec.rb

This will appear after user achieve level 3

Minor fixes to index page

---

app/views/devise/registrations/edit.html.erb
app/views/index/index.html.erb
app/views/layouts/application.html.erb

Made links in footer work
Added basic layout on Change Password page

Put working links in footer

---

app/assets/javascripts/web.js
app/assets/stylesheets/web/forms.scss
app/controllers/phones_controller.rb
app/views/layouts/application.html.erb
app/views/phones/new.html.erb

Added loader
Confirm button disables till the code is sent
Check if the phone nubber wasn't modefied after the code was sent

Minor fixes for phones/new form

---

app/models/document.rb
app/uploaders/upload_uploader.rb
spec/models/account_spec.rb
spec/models/profile_spec.rb
spec/views/documents/edit.html.erb_spec.rb
spec/views/documents/index.html.erb_spec.rb
spec/views/documents/new.html.erb_spec.rb
spec/views/documents/show.html.erb_spec.rb

Added file size, doc_number and file extension validations

Add document validation

---

app/views/documents/_form.html.erb
config/locales/devise.en.yml

Removed 'utility bill' from 'documents' dropdown options and changed notice for successeful email confirmation

---

app/views/admin/accounts/index.html.erb
app/views/admin/profiles/index.html.erb
app/views/admin/profiles/show.html.erb
app/views/admin/websites/_form.html.erb
app/views/admin/websites/index.html.erb
app/views/layouts/admin.html.erb
app/views/layouts/doorkeeper/application.html.erb

Admin panel fixes

---

app/controllers/admin/accounts_controller.rb
app/views/admin/accounts/edit.html.erb
lib/tasks/db_load_fake.rake

Continue implement features regarding PR #118

Continue implement features regarding PR #118

---

app/assets/javascripts/web.js

@gfedorenko Related with issue #195

Fix icon in dropify input

---

.gitignore
docs/index.md
lib/tasks/slate.rake
package.json
yarn.lock

Swagger definitions to Slate compatible markdown

Rake task to generate swagger-slate docs

---

app/controllers/documents_controller.rb
app/controllers/profiles_controller.rb

Fix all entered data which is lost when submitting form with invalid data

---

app/views/devise/sessions/confirm.html.erb

Added autofocus on page to password input

#247 Add focus to email input at page load and password input

---

app/views/admin/shared/_navigation.html.erb
app/views/layouts/shared/_account_footer.html.erb
app/views/layouts/shared/_header.html.erb
config/initializers/devise.rb

We need it to be able to make a sign out from frontend side.

Changed devise logout path from delete to get request

---

.gitignore
Gemfile
Gemfile.lock
app/controllers/api/v1/accounts.rb
app/controllers/api/v1/base.rb
app/controllers/api/v1/helpers.rb
app/controllers/api/v1/phones.rb
app/models/phone.rb
config/initializers/fake_twilio.rb
db/migrate/20180423125629_change_uniq_phones_index.rb
db/schema.rb
spec/api/v1/accounts_spec.rb
spec/api/v1/phones_spec.rb
spec/support/capybara.rb

Fix errors in phones api

---

docs/releases/1.7.0.md

Update 1.7.0 migration steps notes

---

app/controllers/api/v1/phones.rb
app/models/phone.rb

Implement send code API

---

app/helpers/view_helper.rb
app/views/admin/accounts/index.html.erb

Show level and labels on account index page

---

.travis.yml
app/controllers/documents_controller.rb
spec/controllers/documents_controller_spec.rb

Set correct document flash message

---

app/models/label.rb
spec/models/label_spec.rb

Downcase label key and value before save it

---

app/models/document.rb

Add new document type

---

.rubocop.yml
app/api/user_api/v1/base.rb
app/api/user_api/v1/cors/middleware.rb
config/initializers/cors.rb
spec/api/user_api/v1/cors_spec.rb
spec/api/user_api/v1/documents_spec.rb

Borrowed from [peatio cors](https://github.com/rubykube/peatio/blob/master/app/api/api_v2/cors/middleware.rb)
Fixes an issue with document upload

Add CORS middleware

---

app/mailers/account_mailer.rb
app/models/account.rb
docs/specs/event_api.md

Set events with correct devise tokens

---

app/models/label.rb
spec/models/label_spec.rb

Fix labels bug with changing scope

---

app/helpers/application_helper.rb
app/models/label.rb
app/views/admin/accounts/show.html.erb
lib/tasks/add_labels_according_to_level.rake

Squish label fields
Add rake task for update level
Show level mapping at admin panel

Fix issues with levels

---

app/api/management_api/v1/base.rb
app/api/management_api/v1/otp.rb
app/api/user_api/v1/session_jwt_generator.rb
app/models/account.rb
config/initializers/doorkeeper.rb
config/locales/en.yml
config/management_api_v1.yml
docs/api/management_api_v1.md
lib/barong/security/access_token.rb
spec/api/management_api_v1/otp_spec.rb
spec/api/user_api/v1/sessions_spec.rb
spec/factories/account.rb
spec/support/helpers.rb

Relates to https://github.com/rubykube/barong/issues/151

Add otp sign endpoint

---

app/api/user_api/v1/accounts.rb
docs/index.md
spec/api/user_api/v1/accounts_spec.rb

Closes https://github.com/rubykube/barong/issues/480

Add endpoint for resend confirmations

---

app/api/user_api/v1/sessions.rb
spec/api/user_api/v1/sessions_spec.rb

Check 2FA on Barong session api, stub vault request if vault server is down

---

Gemfile.lock
app/api/user_api/v1/helpers.rb
app/api/user_api/v1/phones.rb
app/controllers/phones_controller.rb
lib/phone_utils.rb
spec/api/user_api/v1/phones_spec.rb
spec/controllers/phones_controller_spec.rb

Get international number from phonelib directly

---

app/mailers/account_mailer.rb
app/models/label.rb
docs/api/event_api.md

Applogic don't have a user model, so this info is needed from event's submitter

Add email for Event API system.account.reset_password_token, system.account.unlock_token events, system.document.verified, system.document.rejected

---

Gemfile.lock

http://seclists.org/oss-sec/2018/q2/210

Fix CVE-2018-3760 bug
